GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/12

###
POST http://localhost:3000/subscribers
Content-Type: application/json
{
    "name": "Amazing Person",
    "SubscriberdToChannel: "Web Dev Simplified"

###
DELETE http://localhost:3000/subscribers

###

PATCH http://localhost:3000/subscribers
Content_Type: application/json
{
    "name": "NewName"
}